import type { UserProfile, Task, Step } from "../types";

export const MOCK_USER_PROFILE: UserProfile = {
  user_id: "USER_1027",
  name: "Alex Chen",
  preferred_input: "keyboard",
  preferred_output: "both",
  avg_acknowledgement_time: 7.4,
  avg_execution_time: 18.2,
  avg_errors_per_step: 1.1,
  help_request_rate: 0.35,
  audio_usage_rate: 0.65,
  voice_usage_rate: 0.4,
  ui_preferences: {
    large_buttons: false,
    simplified_text: false,
    audio_priority: false,
    extra_confirmation: false,
  },
};

export const PRESET_TASKS: Record<string, { task: Task; steps: Step[] }> = {
  train: {
    task: {
      task_id: "TASK_TRN_001",
      user_id: "USER_1027",
      original_input: "I want to book a train ticket",
      input_mode: "keyboard",
      normalized_task: "Book a train journey ticket",
      status: "active",
      created_at: new Date().toISOString(),
      completed_at: "",
      overview_stages: [
        "Open the booking app",
        "Enter journey details",
        "Choose a train",
        "Complete payment",
        "Confirm your ticket",
      ],
    },
    steps: [
      {
        step_id: "STEP_TRN_01",
        task_id: "TASK_TRN_001",
        step_number: 1,
        instruction: "Open the booking app on your device.",
        short_instruction: "Open the booking app.",
        difficulty: "low",
        action_type: "click",
        requires_input: true,
        audio_text: "Step 1. Open the booking app on your phone or computer.",
        action_data: {
          choices: [{ id: "c_open", title: "Open Booking App", icon: "Bus", badge: "Ready" }],
        },
      },
      {
        step_id: "STEP_TRN_02",
        task_id: "TASK_TRN_001",
        step_number: 2,
        instruction: "Tap the 'Book Ticket' button on the main screen.",
        short_instruction: "Tap 'Book Ticket'.",
        difficulty: "low",
        action_type: "click",
        requires_input: true,
        audio_text: "Step 2. Tap the Book Ticket button to begin your reservation.",
        action_data: {
          choices: [{ id: "c_book", title: "Tap: Book Ticket", icon: "CheckCircle2", badge: "Action" }],
        },
      },
      {
        step_id: "STEP_TRN_03",
        task_id: "TASK_TRN_001",
        step_number: 3,
        instruction: "Tap the 'From' field to select your departure station.",
        short_instruction: "Tap the 'From' field.",
        difficulty: "low",
        action_type: "click",
        requires_input: true,
        audio_text: "Step 3. Tap the From field.",
        action_data: {
          choices: [{ id: "c_from_field", title: "Tap: 'From' Station Field", icon: "Navigation" }],
        },
      },
      {
        step_id: "STEP_TRN_04",
        task_id: "TASK_TRN_001",
        step_number: 4,
        instruction: "Enter your starting station name.",
        short_instruction: "Enter starting station.",
        difficulty: "medium",
        action_type: "type",
        requires_input: true,
        audio_text: "Step 4. Enter your starting station.",
        action_data: {
          inputLabel: "Starting Station",
          inputPlaceholder: "e.g. Central Station",
          defaultValue: "Central Station",
          choices: [
            { id: "st_1", title: "Central Station" },
            { id: "st_2", title: "Grand Terminal" },
          ],
        },
      },
      {
        step_id: "STEP_TRN_05",
        task_id: "TASK_TRN_001",
        step_number: 5,
        instruction: "Tap the 'To' field to select your destination.",
        short_instruction: "Tap the 'To' field.",
        difficulty: "low",
        action_type: "click",
        requires_input: true,
        audio_text: "Step 5. Tap the To field.",
        action_data: {
          choices: [{ id: "c_to_field", title: "Tap: 'To' Destination Field", icon: "Navigation" }],
        },
      },
      {
        step_id: "STEP_TRN_06",
        task_id: "TASK_TRN_001",
        step_number: 6,
        instruction: "Enter your destination station name.",
        short_instruction: "Enter destination station.",
        difficulty: "medium",
        action_type: "type",
        requires_input: true,
        audio_text: "Step 6. Enter your destination station.",
        action_data: {
          inputLabel: "Destination Station",
          inputPlaceholder: "e.g. North Bay Station",
          defaultValue: "North Bay Station",
          choices: [
            { id: "dt_1", title: "North Bay Station" },
            { id: "dt_2", title: "South Airport Terminal" },
          ],
        },
      },
      {
        step_id: "STEP_TRN_07",
        task_id: "TASK_TRN_001",
        step_number: 7,
        instruction: "Tap the travel date field to open the calendar.",
        short_instruction: "Tap the travel date field.",
        difficulty: "low",
        action_type: "click",
        requires_input: true,
        audio_text: "Step 7. Tap the travel date field to open the calendar.",
        action_data: {
          choices: [{ id: "c_cal", title: "Tap: Date Selector", icon: "Calendar" }],
        },
      },
      {
        step_id: "STEP_TRN_08",
        task_id: "TASK_TRN_001",
        step_number: 8,
        instruction: "Select the day you want to travel from the calendar.",
        short_instruction: "Select travel day.",
        difficulty: "medium",
        action_type: "click",
        requires_input: true,
        audio_text: "Step 8. Select the day you want to travel.",
        action_data: {
          choices: [
            { id: "d_tom", title: "Tomorrow (Friday)", description: "Fastest booking window", badge: "Soonest", icon: "Calendar" },
            { id: "d_sat", title: "This Saturday (Weekend)", description: "Morning and afternoon trains available", icon: "Calendar" },
            { id: "d_mon", title: "Next Monday", description: "Standard business schedule", icon: "Calendar" },
          ],
        },
      },
      {
        step_id: "STEP_TRN_09",
        task_id: "TASK_TRN_001",
        step_number: 9,
        instruction: "Select the date to lock in your calendar choice.",
        short_instruction: "Confirm the date.",
        difficulty: "low",
        action_type: "click",
        requires_input: true,
        audio_text: "Step 9. Confirm your selected date.",
        action_data: {
          choices: [{ id: "c_lock_date", title: "Confirm Selected Date", icon: "CalendarCheck", badge: "Confirmed" }],
        },
      },
      {
        step_id: "STEP_TRN_10",
        task_id: "TASK_TRN_001",
        step_number: 10,
        instruction: "Choose your preferred departure time window.",
        short_instruction: "Choose departure time.",
        difficulty: "medium",
        action_type: "click",
        requires_input: true,
        audio_text: "Step 10. Choose your preferred departure time.",
        action_data: {
          choices: [
            { id: "t_morn", title: "Morning (08:00 AM - 11:00 AM)", description: "Best for daytime transit", badge: "Recommended", icon: "Clock" },
            { id: "t_aft", title: "Afternoon (12:00 PM - 04:00 PM)", description: "Less crowded coaches", icon: "Clock" },
            { id: "t_eve", title: "Evening (05:00 PM - 08:00 PM)", description: "Fast direct route", icon: "Clock" },
          ],
        },
      },
      {
        step_id: "STEP_TRN_11",
        task_id: "TASK_TRN_001",
        step_number: 11,
        instruction: "Look at the list of available trains and schedules.",
        short_instruction: "View available trains.",
        difficulty: "low",
        action_type: "read",
        requires_input: false,
        audio_text: "Step 11. Review the available trains matching your route and time.",
        action_data: {
          readPoints: [
            "Train #102: Express • 08:30 AM → 09:15 AM (45 mins) • On-Time",
            "Train #204: Regional Line • 09:15 AM → 10:25 AM (1 hr 10 mins)",
            "All trains feature step-free boarding and dedicated quiet coaches",
          ],
        },
      },
      {
        step_id: "STEP_TRN_12",
        task_id: "TASK_TRN_001",
        step_number: 12,
        instruction: "Select the train option you want to take.",
        short_instruction: "Select your train.",
        difficulty: "medium",
        action_type: "click",
        requires_input: true,
        audio_text: "Step 12. Tap on the train option you want to book.",
        action_data: {
          choices: [
            { id: "trn_102", title: "Express Train #102 (08:30 AM)", description: "Direct non-stop • 45 minutes • High seat availability", badge: "Fastest", icon: "Bus" },
            { id: "trn_204", title: "Regional Train #204 (09:15 AM)", description: "Scenic line • 1 hr 10 minutes", icon: "Bus" },
          ],
        },
      },
      {
        step_id: "STEP_TRN_13",
        task_id: "TASK_TRN_001",
        step_number: 13,
        instruction: "Choose your seat preference or coach class.",
        short_instruction: "Choose your seat.",
        difficulty: "medium",
        action_type: "select",
        requires_input: true,
        audio_text: "Step 13. Choose your seat or coach class.",
        action_data: {
          choices: [
            { id: "s_win", title: "Window Seat (Coach 2, 14A)", description: "Scenic view • Power plug • Quiet zone", badge: "Popular", icon: "Armchair" },
            { id: "s_ais", title: "Aisle Seat (Coach 2, 14B)", description: "Direct walkway access • Extra legroom", icon: "Armchair" },
            { id: "s_acc", title: "Accessible Seat (Coach 1, 1A)", description: "Level coach entry • Extra wide berth", badge: "Priority", icon: "Accessibility" },
          ],
        },
      },
      {
        step_id: "STEP_TRN_14",
        task_id: "TASK_TRN_001",
        step_number: 14,
        instruction: "Tap the 'Continue' button to proceed to passenger review.",
        short_instruction: "Tap 'Continue'.",
        difficulty: "low",
        action_type: "click",
        requires_input: true,
        audio_text: "Step 14. Tap Continue to save your seat selection.",
        action_data: {
          choices: [{ id: "c_cont", title: "Tap: Continue", icon: "CheckCircle2", badge: "Next" }],
        },
      },
      {
        step_id: "STEP_TRN_15",
        task_id: "TASK_TRN_001",
        step_number: 15,
        instruction: "Review your journey summary details carefully.",
        short_instruction: "Review journey details.",
        difficulty: "low",
        action_type: "confirm",
        requires_input: true,
        audio_text: "Step 15. Check your journey details to ensure your stations and date are correct.",
        action_data: {
          summaryItems: [
            { label: "Route", value: "Central Station → North Bay Station" },
            { label: "Train & Departure", value: "Express #102 at 08:30 AM" },
            { label: "Seat Selection", value: "Coach 2, Seat 14A (Window)" },
            { label: "Passenger Name", value: "Alex Chen" },
            { label: "Ticket Fare", value: "$18.50" },
          ],
        },
      },
      {
        step_id: "STEP_TRN_16",
        task_id: "TASK_TRN_001",
        step_number: 16,
        instruction: "Tap the 'Proceed to Payment' button.",
        short_instruction: "Tap 'Proceed to Payment'.",
        difficulty: "low",
        action_type: "click",
        requires_input: true,
        audio_text: "Step 16. Tap Proceed to Payment.",
        action_data: {
          choices: [{ id: "c_pay_btn", title: "Tap: Proceed to Payment", icon: "CreditCard", badge: "Checkout" }],
        },
      },
      {
        step_id: "STEP_TRN_17",
        task_id: "TASK_TRN_001",
        step_number: 17,
        instruction: "Choose a payment method for your ticket purchase.",
        short_instruction: "Choose payment method.",
        difficulty: "low",
        action_type: "select",
        requires_input: true,
        audio_text: "Step 17. Choose your preferred payment method.",
        action_data: {
          choices: [
            { id: "pm_card", title: "Saved Debit Card (•••• 8092)", description: "Instant secure transaction", badge: "Primary", icon: "CreditCard" },
            { id: "pm_upi", title: "Instant Bank Transfer", description: "Direct bank deduction", icon: "Wallet" },
          ],
        },
      },
      {
        step_id: "STEP_TRN_18",
        task_id: "TASK_TRN_001",
        step_number: 18,
        instruction: "Enter the required payment security details (CVV or PIN).",
        short_instruction: "Enter payment details.",
        difficulty: "medium",
        action_type: "type",
        requires_input: true,
        audio_text: "Step 18. Enter your card security code.",
        action_data: {
          inputLabel: "3-Digit Security Code (CVV)",
          inputPlaceholder: "e.g. 382",
          defaultValue: "382",
          inputType: "number",
        },
      },
      {
        step_id: "STEP_TRN_19",
        task_id: "TASK_TRN_001",
        step_number: 19,
        instruction: "Enter the OTP (One-Time Password) sent to your registered phone.",
        short_instruction: "Enter the OTP.",
        difficulty: "medium",
        action_type: "type",
        requires_input: true,
        audio_text: "Step 19. Enter the one time verification code.",
        action_data: {
          inputLabel: "6-Digit SMS Verification OTP",
          inputPlaceholder: "482910",
          defaultValue: "482910",
          inputType: "number",
        },
      },
      {
        step_id: "STEP_TRN_20",
        task_id: "TASK_TRN_001",
        step_number: 20,
        instruction: "Tap the 'Confirm Payment' button to execute payment.",
        short_instruction: "Tap 'Confirm Payment'.",
        difficulty: "low",
        action_type: "click",
        requires_input: true,
        audio_text: "Step 20. Tap Confirm Payment to complete your booking.",
        action_data: {
          choices: [{ id: "c_conf_pay", title: "Tap: Confirm Payment ($18.50)", icon: "CheckCircle2", badge: "Authorize" }],
        },
      },
      {
        step_id: "STEP_TRN_21",
        task_id: "TASK_TRN_001",
        step_number: 21,
        instruction: "Wait a moment for the digital booking confirmation to generate.",
        short_instruction: "Wait for confirmation.",
        difficulty: "low",
        action_type: "read",
        requires_input: false,
        audio_text: "Step 21. Your payment is verified. Generating your boarding pass and e-ticket.",
        action_data: {
          readPoints: [
            "Payment verified by banking network ✓",
            "Coach 2, Seat 14A locked for passenger Alex Chen ✓",
            "Issuing official e-ticket barcode and reference code...",
          ],
        },
      },
      {
        step_id: "STEP_TRN_22",
        task_id: "TASK_TRN_001",
        step_number: 22,
        instruction: "Your train ticket is booked! Check your confirmation summary below.",
        short_instruction: "Your ticket is booked.",
        difficulty: "low",
        action_type: "confirm",
        requires_input: true,
        audio_text: "Step 22. Your ticket is booked. Everything is ready for your trip.",
        action_data: {
          summaryItems: [
            { label: "Booking Reference", value: "PNR-TRN82910" },
            { label: "Status", value: "Confirmed & Ticket Issued ✓" },
            { label: "Train & Departure", value: "Express #102 • Tomorrow at 08:30 AM" },
            { label: "Assigned Seat", value: "Coach 2, Seat 14A" },
            { label: "Digital Ticket", value: "Sent to SMS & Email" },
          ],
        },
      },
    ],
  },
  transfer: {
    task: {
      task_id: "TASK_BNK_001",
      user_id: "USER_1027",
      original_input: "I want to transfer money",
      input_mode: "keyboard",
      normalized_task: "Transfer money to a contact",
      status: "active",
      created_at: new Date().toISOString(),
      completed_at: "",
      overview_stages: [
        "Open and sign in to your banking app",
        "Choose recipient and enter amount",
        "Review transfer details",
        "Complete verification",
        "Check confirmation",
      ],
    },
    steps: [
      {
        step_id: "STEP_BNK_01",
        task_id: "TASK_BNK_001",
        step_number: 1,
        instruction: "Open your secure banking app on your device.",
        short_instruction: "Open your banking app.",
        difficulty: "low",
        action_type: "click",
        requires_input: true,
        audio_text: "Step 1. Open your banking app on your phone or computer.",
        action_data: {
          choices: [{ id: "b_app", title: "Open Banking App", icon: "CreditCard", badge: "Secure" }],
        },
      },
      {
        step_id: "STEP_BNK_02",
        task_id: "TASK_BNK_001",
        step_number: 2,
        instruction: "Sign in to your account with your passcode or biometric scan.",
        short_instruction: "Sign in to account.",
        difficulty: "low",
        action_type: "click",
        requires_input: true,
        audio_text: "Step 2. Sign in to your banking account.",
        action_data: {
          choices: [{ id: "b_auth", title: "Sign In as Alex Chen (Biometrics Verified ✓)", icon: "UserCheck" }],
        },
      },
      {
        step_id: "STEP_BNK_03",
        task_id: "TASK_BNK_001",
        step_number: 3,
        instruction: "Tap the 'Transfer Money' button on the dashboard.",
        short_instruction: "Tap 'Transfer Money'.",
        difficulty: "low",
        action_type: "click",
        requires_input: true,
        audio_text: "Step 3. Tap Transfer Money to start a new transfer.",
        action_data: {
          choices: [{ id: "b_trf", title: "Tap: Transfer Money", icon: "Wallet", badge: "Action" }],
        },
      },
      {
        step_id: "STEP_BNK_04",
        task_id: "TASK_BNK_001",
        step_number: 4,
        instruction: "Select the person or account you want to send money to.",
        short_instruction: "Select recipient.",
        difficulty: "medium",
        action_type: "click",
        requires_input: true,
        audio_text: "Step 4. Select the person or account you want to send money to.",
        action_data: {
          choices: [
            { id: "rc_1", title: "Jordan Miller (Friend / Utility)", description: "Checking •••• 9281 • Verified Contact", badge: "Frequent", icon: "User" },
            { id: "rc_2", title: "Emma Watson (Family)", description: "Savings •••• 4402", icon: "User" },
            { id: "rc_3", title: "Landlord (Metro Properties)", description: "Direct Deposit •••• 1184", icon: "Home" },
          ],
        },
      },
      {
        step_id: "STEP_BNK_05",
        task_id: "TASK_BNK_001",
        step_number: 5,
        instruction: "Enter the amount of money you want to transfer.",
        short_instruction: "Enter the amount.",
        difficulty: "medium",
        action_type: "type",
        requires_input: true,
        audio_text: "Step 5. Enter the transfer amount in dollars.",
        action_data: {
          inputLabel: "Transfer Amount ($)",
          inputPlaceholder: "e.g. 50.00",
          defaultValue: "50.00",
          inputType: "number",
          choices: [
            { id: "amt_25", title: "$25.00" },
            { id: "amt_50", title: "$50.00" },
            { id: "amt_100", title: "$100.00" },
          ],
        },
      },
      {
        step_id: "STEP_BNK_06",
        task_id: "TASK_BNK_001",
        step_number: 6,
        instruction: "Check that the recipient details and account number are correct.",
        short_instruction: "Check recipient details.",
        difficulty: "low",
        action_type: "confirm",
        requires_input: true,
        audio_text: "Step 6. Check that the recipient name and account details match what you intended.",
        action_data: {
          summaryItems: [
            { label: "Recipient Name", value: "Jordan Miller" },
            { label: "Destination Account", value: "Checking •••• 9281" },
            { label: "Recipient Bank", value: "First National Trust" },
          ],
        },
      },
      {
        step_id: "STEP_BNK_07",
        task_id: "TASK_BNK_001",
        step_number: 7,
        instruction: "Check that the amount and transfer speed are correct.",
        short_instruction: "Check transfer amount.",
        difficulty: "low",
        action_type: "confirm",
        requires_input: true,
        audio_text: "Step 7. Check that the amount is correct.",
        action_data: {
          summaryItems: [
            { label: "Transfer Amount", value: "$50.00" },
            { label: "Funding Account", value: "Everyday Checking (•••• 8092)" },
            { label: "Transfer Fee", value: "$0.00 (Free instant transfer)" },
          ],
        },
      },
      {
        step_id: "STEP_BNK_08",
        task_id: "TASK_BNK_001",
        step_number: 8,
        instruction: "Tap 'Continue' to advance to security verification.",
        short_instruction: "Tap 'Continue'.",
        difficulty: "low",
        action_type: "click",
        requires_input: true,
        audio_text: "Step 8. Tap Continue.",
        action_data: {
          choices: [{ id: "b_cont", title: "Tap: Continue", icon: "CheckCircle2", badge: "Next" }],
        },
      },
      {
        step_id: "STEP_BNK_09",
        task_id: "TASK_BNK_001",
        step_number: 9,
        instruction: "Complete OTP verification sent to your security mobile.",
        short_instruction: "Enter verification OTP.",
        difficulty: "medium",
        action_type: "type",
        requires_input: true,
        audio_text: "Step 9. Complete the one-time security verification.",
        action_data: {
          inputLabel: "6-Digit Bank Verification Code",
          inputPlaceholder: "839201",
          defaultValue: "839201",
          inputType: "number",
        },
      },
      {
        step_id: "STEP_BNK_10",
        task_id: "TASK_BNK_001",
        step_number: 10,
        instruction: "Confirm the transaction to authorize payment.",
        short_instruction: "Confirm transaction.",
        difficulty: "low",
        action_type: "click",
        requires_input: true,
        audio_text: "Step 10. Tap to confirm and authorize the transfer.",
        action_data: {
          choices: [{ id: "b_execute", title: "Tap: Confirm Transfer ($50.00)", icon: "CheckCircle2", badge: "Authorize" }],
        },
      },
      {
        step_id: "STEP_BNK_11",
        task_id: "TASK_BNK_001",
        step_number: 11,
        instruction: "Wait for the bank network to process the instant transfer.",
        short_instruction: "Wait for confirmation.",
        difficulty: "low",
        action_type: "read",
        requires_input: false,
        audio_text: "Step 11. Processing instant transfer. Contacting recipient bank.",
        action_data: {
          readPoints: [
            "Funds deducted from checking •••• 8092 ✓",
            "Direct settlement routing in progress...",
            "Issuing official transaction receipt number",
          ],
        },
      },
      {
        step_id: "STEP_BNK_12",
        task_id: "TASK_BNK_001",
        step_number: 12,
        instruction: "Check that the transaction was successful and save your receipt.",
        short_instruction: "Transaction successful.",
        difficulty: "low",
        action_type: "confirm",
        requires_input: true,
        audio_text: "Step 12. Transfer completed successfully. Jordan Miller has received fifty dollars.",
        action_data: {
          summaryItems: [
            { label: "Status", value: "Completed & Settled ✓" },
            { label: "Amount Sent", value: "$50.00" },
            { label: "Recipient", value: "Jordan Miller (•••• 9281)" },
            { label: "Reference ID", value: "TXN-9028471" },
            { label: "New Checking Balance", value: "$2,400.00" },
          ],
        },
      },
    ],
  },
  coffee: {
    task: {
      task_id: "TASK_COF_001",
      user_id: "USER_1027",
      original_input: "I want to make coffee",
      input_mode: "keyboard",
      normalized_task: "Prepare a fresh cup of hot coffee",
      status: "active",
      created_at: new Date().toISOString(),
      completed_at: "",
      overview_stages: [
        "Gather mug and ingredients",
        "Measure and heat milk on stove",
        "Add coffee powder and sugar",
        "Stir and brew coffee",
        "Pour and serve hot coffee",
      ],
    },
    steps: [
      {
        step_id: "STEP_COF_01",
        task_id: "TASK_COF_001",
        step_number: 1,
        instruction: "Take a clean mug from the kitchen cabinet and place it on your counter.",
        short_instruction: "Take a clean mug.",
        difficulty: "low",
        action_type: "click",
        requires_input: true,
        audio_text: "Step 1. Take a clean mug and place it on your counter.",
        action_data: {
          choices: [{ id: "c_mug", title: "Clean Mug Ready on Counter ✓", icon: "CheckCircle2", badge: "Ready" }],
        },
      },
      {
        step_id: "STEP_COF_02",
        task_id: "TASK_COF_001",
        step_number: 2,
        instruction: "Take your coffee powder jar from the shelf.",
        short_instruction: "Take your coffee powder.",
        difficulty: "low",
        action_type: "click",
        requires_input: true,
        audio_text: "Step 2. Take your coffee powder and place it near your mug.",
        action_data: {
          choices: [{ id: "c_powder", title: "Coffee Powder Jar Ready ✓", icon: "CheckCircle2" }],
        },
      },
      {
        step_id: "STEP_COF_03",
        task_id: "TASK_COF_001",
        step_number: 3,
        instruction: "Take about one cup of milk from the refrigerator.",
        short_instruction: "Take one cup of milk.",
        difficulty: "low",
        action_type: "click",
        requires_input: true,
        audio_text: "Step 3. Take about one cup of milk.",
        action_data: {
          choices: [{ id: "c_milk", title: "1 Cup of Milk Measured ✓", icon: "CheckCircle2" }],
        },
      },
      {
        step_id: "STEP_COF_04",
        task_id: "TASK_COF_001",
        step_number: 4,
        instruction: "Take a small vessel or saucepan.",
        short_instruction: "Take a small saucepan.",
        difficulty: "low",
        action_type: "click",
        requires_input: true,
        audio_text: "Step 4. Take a small vessel or saucepan.",
        action_data: {
          choices: [{ id: "c_vessel", title: "Saucepan Placed on Counter ✓", icon: "CheckCircle2" }],
        },
      },
      {
        step_id: "STEP_COF_05",
        task_id: "TASK_COF_001",
        step_number: 5,
        instruction: "Pour the cup of milk into the saucepan.",
        short_instruction: "Pour milk into saucepan.",
        difficulty: "low",
        action_type: "click",
        requires_input: true,
        audio_text: "Step 5. Pour the milk into the vessel.",
        action_data: {
          choices: [{ id: "c_pour", title: "Milk Poured into Saucepan ✓", icon: "CheckCircle2" }],
        },
      },
      {
        step_id: "STEP_COF_06",
        task_id: "TASK_COF_001",
        step_number: 6,
        instruction: "Place the vessel safely onto the stove burner.",
        short_instruction: "Place vessel on stove.",
        difficulty: "low",
        action_type: "click",
        requires_input: true,
        audio_text: "Step 6. Place the vessel on the stove.",
        action_data: {
          choices: [{ id: "c_on_stove", title: "Vessel Placed on Burner ✓", icon: "CheckCircle2" }],
        },
      },
      {
        step_id: "STEP_COF_07",
        task_id: "TASK_COF_001",
        step_number: 7,
        instruction: "Turn on the stove burner to medium heat.",
        short_instruction: "Turn on the stove.",
        difficulty: "medium",
        action_type: "click",
        requires_input: true,
        audio_text: "Step 7. Turn on the stove to medium heat.",
        action_data: {
          choices: [
            { id: "st_med", title: "Turn Stove to Medium Flame", description: "Safe and gentle heating", badge: "Recommended", icon: "Zap" },
            { id: "st_low", title: "Turn Stove to Low Flame", description: "Slower heating", icon: "Zap" },
          ],
        },
      },
      {
        step_id: "STEP_COF_08",
        task_id: "TASK_COF_001",
        step_number: 8,
        instruction: "Add 1 to 2 teaspoons of coffee powder into the warming milk.",
        short_instruction: "Add coffee powder.",
        difficulty: "low",
        action_type: "click",
        requires_input: true,
        audio_text: "Step 8. Add coffee powder into the milk.",
        action_data: {
          choices: [
            { id: "c_powder_1", title: "Add 1 Teaspoon (Mild Coffee)", icon: "CheckCircle2" },
            { id: "c_powder_2", title: "Add 2 Teaspoons (Strong Coffee)", badge: "Strong", icon: "CheckCircle2" },
          ],
        },
      },
      {
        step_id: "STEP_COF_09",
        task_id: "TASK_COF_001",
        step_number: 9,
        instruction: "Add sugar if you want sugar in your coffee.",
        short_instruction: "Add sugar if desired.",
        difficulty: "low",
        action_type: "select",
        requires_input: true,
        audio_text: "Step 9. Add sugar if you like your coffee sweet.",
        action_data: {
          choices: [
            { id: "sug_1", title: "Add 1 Spoon Sugar", description: "Light sweetness", icon: "Sparkles" },
            { id: "sug_2", title: "Add 2 Spoons Sugar", description: "Regular sweetness", badge: "Popular", icon: "Sparkles" },
            { id: "sug_0", title: "No Sugar (Plain / Black)", description: "Zero sugar added", icon: "CheckCircle2" },
          ],
        },
      },
      {
        step_id: "STEP_COF_10",
        task_id: "TASK_COF_001",
        step_number: 10,
        instruction: "Stir the mixture gently with a spoon until the powder dissolves.",
        short_instruction: "Stir the mixture.",
        difficulty: "low",
        action_type: "click",
        requires_input: true,
        audio_text: "Step 10. Stir the mixture gently with a spoon.",
        action_data: {
          choices: [{ id: "c_stir", title: "Stirred Mixture with Spoon ✓", icon: "CheckCircle2" }],
        },
      },
      {
        step_id: "STEP_COF_11",
        task_id: "TASK_COF_001",
        step_number: 11,
        instruction: "Let the coffee heat gently for about 5 to 8 minutes. Watch for rising foam.",
        short_instruction: "Heat for 5–8 minutes.",
        difficulty: "medium",
        action_type: "read",
        requires_input: false,
        audio_text: "Step 11. Let the coffee heat for about five to eight minutes. Keep an eye on the vessel so it does not spill.",
        action_data: {
          readPoints: [
            "Watch the milk as it warms up over medium flame",
            "When small bubbles rise at the edge, it is nearing boiling point",
            "Do not leave stove unattended to prevent boiling over",
          ],
        },
      },
      {
        step_id: "STEP_COF_12",
        task_id: "TASK_COF_001",
        step_number: 12,
        instruction: "Turn off the stove burner once the coffee begins to rise.",
        short_instruction: "Turn off the stove.",
        difficulty: "low",
        action_type: "click",
        requires_input: true,
        audio_text: "Step 12. Turn off the stove safely.",
        action_data: {
          choices: [{ id: "c_stove_off", title: "Turned Off Stove Burner ✓", icon: "CheckCircle2", badge: "Stove Off" }],
        },
      },
      {
        step_id: "STEP_COF_13",
        task_id: "TASK_COF_001",
        step_number: 13,
        instruction: "Carefully pour the hot coffee into your clean mug.",
        short_instruction: "Pour coffee into mug.",
        difficulty: "medium",
        action_type: "click",
        requires_input: true,
        audio_text: "Step 13. Carefully pour the coffee into your mug.",
        action_data: {
          choices: [{ id: "c_pour_mug", title: "Coffee Poured into Mug ✓", icon: "CheckCircle2" }],
        },
      },
      {
        step_id: "STEP_COF_14",
        task_id: "TASK_COF_001",
        step_number: 14,
        instruction: "Your hot coffee is ready! Enjoy your drink.",
        short_instruction: "Your coffee is ready.",
        difficulty: "low",
        action_type: "confirm",
        requires_input: true,
        audio_text: "Step 14. Your coffee is ready. Take small sips and enjoy.",
        action_data: {
          summaryItems: [
            { label: "Drink", value: "Fresh Hot Milk Coffee ☕" },
            { label: "Container", value: "In your clean mug" },
            { label: "Stove Status", value: "Turned Off Safely ✓" },
            { label: "Temperature", value: "Hot (Sip carefully)" },
          ],
        },
      },
    ],
  },
  doctor: {
    task: {
      task_id: "TASK_DOC_001",
      user_id: "USER_1027",
      original_input: "Book a doctor's appointment",
      input_mode: "keyboard",
      normalized_task: "Schedule a medical consultation appointment",
      status: "active",
      created_at: new Date().toISOString(),
      completed_at: "",
      overview_stages: [
        "Open booking portal",
        "Choose doctor and specialty",
        "Select date and time",
        "Enter contact details",
        "Confirm appointment",
      ],
    },
    steps: [
      {
        step_id: "STEP_DOC_01",
        task_id: "TASK_DOC_001",
        step_number: 1,
        instruction: "Open the clinic appointment booking portal.",
        short_instruction: "Open clinic portal.",
        difficulty: "low",
        action_type: "click",
        requires_input: true,
        audio_text: "Step 1. Open the clinic booking portal.",
        action_data: {
          choices: [{ id: "d_open", title: "Open Clinic Portal", icon: "Hospital", badge: "Ready" }],
        },
      },
      {
        step_id: "STEP_DOC_02",
        task_id: "TASK_DOC_001",
        step_number: 2,
        instruction: "Tap the 'Book Appointment' button on the clinic home screen.",
        short_instruction: "Tap 'Book Appointment'.",
        difficulty: "low",
        action_type: "click",
        requires_input: true,
        audio_text: "Step 2. Tap Book Appointment.",
        action_data: {
          choices: [{ id: "d_tap_book", title: "Tap: Book Appointment", icon: "CheckCircle2", badge: "Action" }],
        },
      },
      {
        step_id: "STEP_DOC_03",
        task_id: "TASK_DOC_001",
        step_number: 3,
        instruction: "Choose the medical specialty you need to consult.",
        short_instruction: "Choose medical specialty.",
        difficulty: "medium",
        action_type: "click",
        requires_input: true,
        audio_text: "Step 3. Choose the medical specialty you need.",
        action_data: {
          choices: [
            { id: "sp_gp", title: "General Practitioner (Family Doctor)", description: "Routine illness, checkups, prescriptions", badge: "Most Common", icon: "Stethoscope" },
            { id: "sp_card", title: "Cardiologist (Heart Health)", description: "Blood pressure, heart rhythm checks", icon: "HeartPulse" },
            { id: "sp_orth", title: "Orthopedic (Joints & Bones)", description: "Joint pain, sprains, back support", icon: "Activity" },
            { id: "sp_derm", title: "Dermatologist (Skin Care)", description: "Skin rashes, allergies", icon: "Sparkles" },
          ],
        },
      },
      {
        step_id: "STEP_DOC_04",
        task_id: "TASK_DOC_001",
        step_number: 4,
        instruction: "Select the doctor you want to consult with.",
        short_instruction: "Select your doctor.",
        difficulty: "medium",
        action_type: "click",
        requires_input: true,
        audio_text: "Step 4. Select your preferred doctor.",
        action_data: {
          choices: [
            { id: "doc_1", title: "Dr. Sarah Jenkins, MD", description: "14 years experience • Primary Care • 4.9 ★", badge: "Earliest Slot", icon: "UserCheck" },
            { id: "doc_2", title: "Dr. Michael Aris, MD", description: "18 years experience • Senior Consultant • 4.8 ★", icon: "UserCheck" },
          ],
        },
      },
      {
        step_id: "STEP_DOC_05",
        task_id: "TASK_DOC_001",
        step_number: 5,
        instruction: "Tap the appointment date field to choose a day.",
        short_instruction: "Tap date field.",
        difficulty: "low",
        action_type: "click",
        requires_input: true,
        audio_text: "Step 5. Tap the appointment date field.",
        action_data: {
          choices: [{ id: "d_tap_date", title: "Tap: Appointment Date Field", icon: "Calendar" }],
        },
      },
      {
        step_id: "STEP_DOC_06",
        task_id: "TASK_DOC_001",
        step_number: 6,
        instruction: "Select the day you want to visit the clinic.",
        short_instruction: "Select clinic date.",
        difficulty: "medium",
        action_type: "click",
        requires_input: true,
        audio_text: "Step 6. Select your preferred day.",
        action_data: {
          choices: [
            { id: "dt_tom", title: "Tomorrow (Friday)", description: "Next day opening", badge: "Earliest", icon: "Calendar" },
            { id: "dt_sat", title: "Saturday Morning", description: "Weekend clinic", icon: "Calendar" },
            { id: "dt_mon", title: "Next Monday", description: "Flexible slots", icon: "Calendar" },
          ],
        },
      },
      {
        step_id: "STEP_DOC_07",
        task_id: "TASK_DOC_001",
        step_number: 7,
        instruction: "Tap the appointment time slot field.",
        short_instruction: "Tap time slot.",
        difficulty: "low",
        action_type: "click",
        requires_input: true,
        audio_text: "Step 7. Tap the appointment time slot.",
        action_data: {
          choices: [{ id: "d_tap_time", title: "Tap: Time Slot Selector", icon: "Clock" }],
        },
      },
      {
        step_id: "STEP_DOC_08",
        task_id: "TASK_DOC_001",
        step_number: 8,
        instruction: "Select your preferred appointment time from the available options.",
        short_instruction: "Choose appointment time.",
        difficulty: "high",
        action_type: "click",
        requires_input: true,
        audio_text: "Step 8. Choose an appointment time. Tap one of the available times below.",
        action_data: {
          choices: [
            { id: "tm_0930", title: "09:30 AM (Morning)", description: "Prompt check-in • 45 min duration", badge: "Popular", icon: "Clock" },
            { id: "tm_1100", title: "11:00 AM (Late Morning)", description: "Low wait time", icon: "Clock" },
            { id: "tm_1430", title: "02:30 PM (Afternoon)", description: "Post-lunch opening", icon: "Clock" },
          ],
        },
      },
      {
        step_id: "STEP_DOC_09",
        task_id: "TASK_DOC_001",
        step_number: 9,
        instruction: "Enter your basic contact details for appointment confirmation.",
        short_instruction: "Enter your details.",
        difficulty: "medium",
        action_type: "type",
        requires_input: true,
        audio_text: "Step 9. Enter your contact details.",
        action_data: {
          inputLabel: "Patient Name & Phone Number",
          inputPlaceholder: "Alex Chen, (555) 019-2834",
          defaultValue: "Alex Chen, (555) 019-2834",
          inputType: "text",
        },
      },
      {
        step_id: "STEP_DOC_10",
        task_id: "TASK_DOC_001",
        step_number: 10,
        instruction: "Review your appointment summary details carefully.",
        short_instruction: "Review appointment.",
        difficulty: "low",
        action_type: "confirm",
        requires_input: true,
        audio_text: "Step 10. Review your appointment details.",
        action_data: {
          summaryItems: [
            { label: "Doctor", value: "Dr. Sarah Jenkins, MD (General Practitioner)" },
            { label: "Date & Time", value: "Tomorrow at 09:30 AM" },
            { label: "Patient", value: "Alex Chen (ID: USER_1027)" },
            { label: "Location", value: "City Health Clinic (Room 304)" },
            { label: "Consultation Fee", value: "$0.00 (Insurance Covered)" },
          ],
        },
      },
      {
        step_id: "STEP_DOC_11",
        task_id: "TASK_DOC_001",
        step_number: 11,
        instruction: "Tap the 'Confirm Appointment' button to finalize your booking.",
        short_instruction: "Tap 'Confirm Appointment'.",
        difficulty: "low",
        action_type: "click",
        requires_input: true,
        audio_text: "Step 11. Tap Confirm Appointment.",
        action_data: {
          choices: [{ id: "d_tap_confirm", title: "Tap: Confirm Appointment", icon: "CheckCircle2", badge: "Finalize" }],
        },
      },
      {
        step_id: "STEP_DOC_12",
        task_id: "TASK_DOC_001",
        step_number: 12,
        instruction: "Wait for the clinic server to confirm your scheduled appointment.",
        short_instruction: "Wait for confirmation.",
        difficulty: "low",
        action_type: "read",
        requires_input: false,
        audio_text: "Step 12. Processing confirmation with the clinic system.",
        action_data: {
          readPoints: [
            "Physician schedule locked for tomorrow 09:30 AM ✓",
            "Medical records linked for Alex Chen ✓",
            "Dispatching SMS confirmation to (555) 019-2834",
          ],
        },
      },
      {
        step_id: "STEP_DOC_13",
        task_id: "TASK_DOC_001",
        step_number: 13,
        instruction: "Your appointment is confirmed! Check your booking summary below.",
        short_instruction: "Appointment confirmed.",
        difficulty: "low",
        action_type: "confirm",
        requires_input: true,
        audio_text: "Step 13. Your doctor appointment is confirmed. See you tomorrow at 09:30 AM.",
        action_data: {
          summaryItems: [
            { label: "Status", value: "Confirmed & Locked ✓" },
            { label: "Appointment ID", value: "APT-84920" },
            { label: "Time", value: "Tomorrow, 09:30 AM" },
            { label: "Clinic Wing", value: "City Health Clinic, Room 304" },
            { label: "Reminders", value: "SMS sent with directions" },
          ],
        },
      },
    ],
  },
};

export function generateGenericSteps(taskTitle: string): { task: Task; steps: Step[] } {
  const taskId = `TASK_GEN_${Date.now()}`;
  return {
    task: {
      task_id: taskId,
      user_id: "USER_1027",
      original_input: taskTitle,
      input_mode: "text",
      normalized_task: taskTitle,
      status: "active",
      created_at: new Date().toISOString(),
      completed_at: "",
      overview_stages: [
        `Open service for ${taskTitle}`,
        "Enter required details",
        "Review specifications",
        "Complete submission",
      ],
    },
    steps: [
      {
        step_id: `${taskId}_01`,
        task_id: taskId,
        step_number: 1,
        instruction: `Open the relevant service application for "${taskTitle}".`,
        short_instruction: "Open service app.",
        difficulty: "low",
        action_type: "click",
        requires_input: true,
        audio_text: `Step 1. Open the application for ${taskTitle}.`,
        action_data: {
          choices: [{ id: "g_open", title: `Open App for ${taskTitle}`, icon: "CheckCircle2", badge: "Start" }],
        },
      },
      {
        step_id: `${taskId}_02`,
        task_id: taskId,
        step_number: 2,
        instruction: "Tap the 'Start New Request' button on screen.",
        short_instruction: "Tap 'Start New Request'.",
        difficulty: "low",
        action_type: "click",
        requires_input: true,
        audio_text: "Step 2. Tap Start New Request.",
        action_data: {
          choices: [{ id: "g_start", title: "Tap: Start New Request", icon: "CheckCircle2", badge: "Action" }],
        },
      },
      {
        step_id: `${taskId}_03`,
        task_id: taskId,
        step_number: 3,
        instruction: "Tap the primary option or category field.",
        short_instruction: "Tap option field.",
        difficulty: "low",
        action_type: "click",
        requires_input: true,
        audio_text: "Step 3. Tap the option field.",
        action_data: {
          choices: [{ id: "g_tap_fld", title: "Tap Option Field", icon: "CheckCircle2" }],
        },
      },
      {
        step_id: `${taskId}_04`,
        task_id: taskId,
        step_number: 4,
        instruction: "Select the option that best fits what you need.",
        short_instruction: "Select your option.",
        difficulty: "medium",
        action_type: "click",
        requires_input: true,
        audio_text: "Step 4. Select your preferred option.",
        action_data: {
          choices: [
            { id: "g_opt1", title: "Standard Option", description: "Standard turnaround and configuration", badge: "Recommended", icon: "CheckCircle2" },
            { id: "g_opt2", title: "Priority Option", description: "Fastest turnaround mode", icon: "Sparkles" },
          ],
        },
      },
      {
        step_id: `${taskId}_05`,
        task_id: taskId,
        step_number: 5,
        instruction: "Tap the details input field.",
        short_instruction: "Tap details field.",
        difficulty: "low",
        action_type: "click",
        requires_input: true,
        audio_text: "Step 5. Tap the details input field.",
        action_data: {
          choices: [{ id: "g_tap_txt", title: "Tap: Details Field", icon: "CheckCircle2" }],
        },
      },
      {
        step_id: `${taskId}_06`,
        task_id: taskId,
        step_number: 6,
        instruction: "Enter your contact or account information.",
        short_instruction: "Enter your details.",
        difficulty: "medium",
        action_type: "type",
        requires_input: true,
        audio_text: "Step 6. Enter your details.",
        action_data: {
          inputLabel: "Contact Information",
          inputPlaceholder: "Alex Chen, (555) 019-2834",
          defaultValue: "Alex Chen, (555) 019-2834",
          inputType: "text",
        },
      },
      {
        step_id: `${taskId}_07`,
        task_id: taskId,
        step_number: 7,
        instruction: "Tap 'Continue' to advance to the review screen.",
        short_instruction: "Tap 'Continue'.",
        difficulty: "low",
        action_type: "click",
        requires_input: true,
        audio_text: "Step 7. Tap Continue.",
        action_data: {
          choices: [{ id: "g_cont", title: "Tap: Continue", icon: "CheckCircle2", badge: "Next" }],
        },
      },
      {
        step_id: `${taskId}_08`,
        task_id: taskId,
        step_number: 8,
        instruction: "Review your summary details to make sure everything is accurate.",
        short_instruction: "Review your details.",
        difficulty: "low",
        action_type: "confirm",
        requires_input: true,
        audio_text: "Step 8. Review your information.",
        action_data: {
          summaryItems: [
            { label: "Task Goal", value: taskTitle },
            { label: "Applicant", value: "Alex Chen" },
            { label: "Status", value: "Verified & Ready" },
          ],
        },
      },
      {
        step_id: `${taskId}_09`,
        task_id: taskId,
        step_number: 9,
        instruction: "Tap 'Confirm and Submit' to execute your request.",
        short_instruction: "Tap 'Confirm and Submit'.",
        difficulty: "low",
        action_type: "click",
        requires_input: true,
        audio_text: "Step 9. Tap Confirm and Submit.",
        action_data: {
          choices: [{ id: "g_sub", title: "Tap: Confirm and Submit", icon: "CheckCircle2", badge: "Execute" }],
        },
      },
      {
        step_id: `${taskId}_10`,
        task_id: taskId,
        step_number: 10,
        instruction: "Wait for the digital confirmation receipt to be generated.",
        short_instruction: "Wait for confirmation.",
        difficulty: "low",
        action_type: "read",
        requires_input: false,
        audio_text: "Step 10. Generating confirmation receipt.",
        action_data: {
          readPoints: [
            `Request for "${taskTitle}" received ✓`,
            "Security verification passed ✓",
            "Issuing reference identifier...",
          ],
        },
      },
      {
        step_id: `${taskId}_11`,
        task_id: taskId,
        step_number: 11,
        instruction: `Your request for "${taskTitle}" is completed! Check your confirmation below.`,
        short_instruction: "Request completed.",
        difficulty: "low",
        action_type: "confirm",
        requires_input: true,
        audio_text: `Step 11. Your request for ${taskTitle} has been completed successfully.`,
        action_data: {
          summaryItems: [
            { label: "Goal", value: taskTitle },
            { label: "Status", value: "Successfully Completed ✓" },
            { label: "Reference Code", value: `REF-${Date.now().toString().slice(-6)}` },
            { label: "Receipt", value: "Saved to profile history" },
          ],
        },
      },
    ],
  };
}
