import type { UserProfile, Task, Step } from "../types";

export const MOCK_USER_PROFILE: UserProfile = {
  user_id: "USER_1027",
  name: "Alex Chen",
  preferred_input: "keyboard",
  preferred_output: "both",
  avg_acknowledgement_time: 7.4,
  avg_execution_time: 18.2,
  avg_errors_per_step: 1.1,
  help_request_rate: 0.35,
  audio_usage_rate: 0.65,
  voice_usage_rate: 0.4,
  ui_preferences: {
    large_buttons: false,
    simplified_text: false,
    audio_priority: false,
    extra_confirmation: false,
  },
};

export const PRESET_TASKS: Record<string, { task: Task; steps: Step[] }> = {
  doctor: {
    task: {
      task_id: "TASK_DOC_001",
      user_id: "USER_1027",
      original_input: "Book a doctor's appointment",
      input_mode: "keyboard",
      normalized_task: "Schedule a medical consultation appointment",
      status: "active",
      created_at: new Date().toISOString(),
      completed_at: "",
    },
    steps: [
      {
        step_id: "STEP_DOC_01",
        task_id: "TASK_DOC_001",
        step_number: 1,
        instruction: "Select the hospital or community healthcare center nearest to you.",
        short_instruction: "Choose your hospital.",
        difficulty: "low",
        action_type: "click",
        requires_input: true,
        audio_text: "Step 1. Choose the hospital or medical clinic where you want to have your appointment.",
        action_data: {
          choices: [
            {
              id: "hosp_1",
              title: "City General Hospital",
              description: "1.2 miles away • 24/7 Emergency Care & Outpatient",
              badge: "Closest",
              icon: "Building2",
            },
            {
              id: "hosp_2",
              title: "St. Mary's Wellness Pavilion",
              description: "2.8 miles away • Specialty Care & Lab Services",
              badge: "High Availability",
              icon: "Hospital",
            },
            {
              id: "hosp_3",
              title: "Riverside Family Health Center",
              description: "3.5 miles away • Walk-in clinic & family physicians",
              badge: "Low Wait Time",
              icon: "Cross",
            },
          ],
        },
      },
      {
        step_id: "STEP_DOC_02",
        task_id: "TASK_DOC_001",
        step_number: 2,
        instruction: "Select the medical specialty or department for your consultation.",
        short_instruction: "Pick the department.",
        difficulty: "medium",
        action_type: "select",
        requires_input: true,
        audio_text: "Step 2. Select the department or medical field you need to consult.",
        action_data: {
          choices: [
            {
              id: "dept_1",
              title: "General Medicine & Primary Care",
              description: "Coughs, fevers, routine checkups, general wellness",
              badge: "Most Common",
              icon: "Stethoscope",
            },
            {
              id: "dept_2",
              title: "Cardiology & Heart Health",
              description: "Blood pressure, chest checks, cardiovascular health",
              icon: "HeartPulse",
            },
            {
              id: "dept_3",
              title: "Orthopedics & Joint Care",
              description: "Bones, sprains, back pain, joint mobility",
              icon: "Activity",
            },
            {
              id: "dept_4",
              title: "Dermatology & Skin Care",
              description: "Skin conditions, rashes, allergies, dermatology",
              icon: "Sparkles",
            },
          ],
        },
      },
      {
        step_id: "STEP_DOC_03",
        task_id: "TASK_DOC_001",
        step_number: 3,
        instruction: "Select the doctor you want to consult based on availability and credentials.",
        short_instruction: "Choose your doctor.",
        difficulty: "high",
        action_type: "click",
        requires_input: true,
        audio_text: "Step 3. Choose the doctor you want to see.",
        action_data: {
          choices: [
            {
              id: "doc_1",
              title: "Dr. Sarah Jenkins, MD",
              description: "14 years experience • English, Spanish • 4.9 ★ (340 reviews)",
              badge: "Next available: Tomorrow 10:00 AM",
              icon: "UserCheck",
            },
            {
              id: "doc_2",
              title: "Dr. Michael Aris, MD",
              description: "18 years experience • Internal Medicine specialist • 4.8 ★",
              badge: "Next available: Thursday 02:30 PM",
              icon: "UserCheck",
            },
            {
              id: "doc_3",
              title: "Dr. Elena Rostova, PhD",
              description: "9 years experience • Preventive care focus • 5.0 ★",
              badge: "Next available: Today 04:15 PM",
              icon: "UserCheck",
            },
          ],
        },
      },
      {
        step_id: "STEP_DOC_04",
        task_id: "TASK_DOC_001",
        step_number: 4,
        instruction: "Select your preferred date and time slot for the consultation.",
        short_instruction: "Pick a time slot.",
        difficulty: "medium",
        action_type: "click",
        requires_input: true,
        audio_text: "Step 4. Pick a day and time that works best for your schedule.",
        action_data: {
          choices: [
            {
              id: "time_1",
              title: "Tomorrow (Morning)",
              description: "10:00 AM - 10:45 AM • In-person clinic visit",
              badge: "Fastest",
              icon: "Calendar",
            },
            {
              id: "time_2",
              title: "Tomorrow (Afternoon)",
              description: "02:30 PM - 03:15 PM • In-person clinic visit",
              icon: "Clock",
            },
            {
              id: "time_3",
              title: "Friday (Morning)",
              description: "11:15 AM - 12:00 PM • In-person clinic visit",
              icon: "Calendar",
            },
            {
              id: "time_4",
              title: "Saturday (Weekend slot)",
              description: "09:30 AM - 10:15 AM • In-person clinic visit",
              icon: "CalendarCheck",
            },
          ],
        },
      },
      {
        step_id: "STEP_DOC_05",
        task_id: "TASK_DOC_001",
        step_number: 5,
        instruction: "Review your appointment summary and confirm to finalize your booking.",
        short_instruction: "Confirm appointment.",
        difficulty: "low",
        action_type: "confirm",
        requires_input: true,
        audio_text: "Step 5. Check your appointment summary, then press confirm to complete.",
        action_data: {
          summaryItems: [
            { label: "Hospital", value: "City General Hospital (Main Wing)" },
            { label: "Department", value: "General Medicine & Primary Care" },
            { label: "Physician", value: "Dr. Sarah Jenkins, MD" },
            { label: "Time Slot", value: "Tomorrow, 10:00 AM - 10:45 AM" },
            { label: "Patient", value: "Alex Chen (ID: USER_1027)" },
            { label: "Coverage", value: "Fully Covered by Insurance ($0 Due)" },
          ],
        },
      },
    ],
  },
  bus: {
    task: {
      task_id: "TASK_BUS_001",
      user_id: "USER_1027",
      original_input: "Book a bus ticket",
      input_mode: "keyboard",
      normalized_task: "Purchase an intercity bus ticket",
      status: "active",
      created_at: new Date().toISOString(),
      completed_at: "",
    },
    steps: [
      {
        step_id: "STEP_BUS_01",
        task_id: "TASK_BUS_001",
        step_number: 1,
        instruction: "Choose your departure city and destination.",
        short_instruction: "Choose where you are going.",
        difficulty: "low",
        action_type: "click",
        requires_input: true,
        audio_text: "Choose where you want to travel from and to.",
        action_data: {
          choices: [
            { id: "route_1", title: "Downtown Station → Central City", description: "Express route • 1 hr 15 mins", badge: "Most Popular", icon: "Bus" },
            { id: "route_2", title: "Downtown Station → West Valley", description: "Regional line • 2 hrs 10 mins", icon: "Bus" },
            { id: "route_3", title: "Downtown Station → Airport Terminal", description: "Direct shuttle • 45 mins", badge: "Direct", icon: "Bus" },
          ],
        },
      },
      {
        step_id: "STEP_BUS_02",
        task_id: "TASK_BUS_001",
        step_number: 2,
        instruction: "Select travel date and departure timing.",
        short_instruction: "Pick your departure time.",
        difficulty: "medium",
        action_type: "click",
        requires_input: true,
        audio_text: "Pick the departure time for your bus ride.",
        action_data: {
          choices: [
            { id: "btime_1", title: "Morning Bus — 08:30 AM", description: "Arrives 09:45 AM • High seat availability", badge: "$14.50", icon: "Clock" },
            { id: "btime_2", title: "Afternoon Bus — 01:00 PM", description: "Arrives 02:15 PM • Medium seat availability", badge: "$14.50", icon: "Clock" },
            { id: "btime_3", title: "Evening Bus — 05:45 PM", description: "Arrives 07:00 PM • Fast transit", badge: "$16.00", icon: "Clock" },
          ],
        },
      },
      {
        step_id: "STEP_BUS_03",
        task_id: "TASK_BUS_001",
        step_number: 3,
        instruction: "Select your preferred seat zone on the bus.",
        short_instruction: "Pick your seat.",
        difficulty: "medium",
        action_type: "select",
        requires_input: true,
        audio_text: "Pick the seat type you prefer on the coach.",
        action_data: {
          choices: [
            { id: "seat_1", title: "Forward Window Seat (3A)", description: "Near front door • Easy boarding • Good scenery", badge: "Recommended", icon: "Armchair" },
            { id: "seat_2", title: "Forward Aisle Seat (3B)", description: "Direct aisle access • Extra leg space", icon: "Armchair" },
            { id: "seat_3", title: "Accessibility Priority Row (1A)", description: "Zero-step entry • Direct wheelchair or luggage space", badge: "Accessible", icon: "Accessibility" },
          ],
        },
      },
      {
        step_id: "STEP_BUS_04",
        task_id: "TASK_BUS_001",
        step_number: 4,
        instruction: "Review passenger ticket and confirm purchase.",
        short_instruction: "Confirm your bus ticket.",
        difficulty: "low",
        action_type: "confirm",
        requires_input: true,
        audio_text: "Review your travel details and press confirm.",
        action_data: {
          summaryItems: [
            { label: "Trip", value: "Downtown Station → Central City" },
            { label: "Departure", value: "Tomorrow at 08:30 AM" },
            { label: "Seat", value: "Seat 3A (Forward Window)" },
            { label: "Passenger", value: "Alex Chen" },
            { label: "Fare", value: "$14.50 (Paid via Saved Card)" },
          ],
        },
      },
    ],
  },
  transfer: {
    task: {
      task_id: "TASK_BNK_001",
      user_id: "USER_1027",
      original_input: "Make a bank transfer",
      input_mode: "keyboard",
      normalized_task: "Transfer money to a saved contact",
      status: "active",
      created_at: new Date().toISOString(),
      completed_at: "",
    },
    steps: [
      {
        step_id: "STEP_BNK_01",
        task_id: "TASK_BNK_001",
        step_number: 1,
        instruction: "Select the verified recipient for your transfer.",
        short_instruction: "Who are you sending money to?",
        difficulty: "low",
        action_type: "click",
        requires_input: true,
        audio_text: "Select the person or organization you want to send money to.",
        action_data: {
          choices: [
            { id: "recip_1", title: "Jordan Miller (Electric Utility)", description: "Account •••• 9281 • Verified Biller", badge: "Frequent", icon: "Building" },
            { id: "recip_2", title: "Emma Watson (Family)", description: "Checking •••• 4402 • Verified Contact", icon: "User" },
            { id: "recip_3", title: "Landlord (Metro Properties)", description: "Direct Deposit •••• 1184", icon: "Home" },
          ],
        },
      },
      {
        step_id: "STEP_BNK_02",
        task_id: "TASK_BNK_001",
        step_number: 2,
        instruction: "Enter the transfer amount in US Dollars.",
        short_instruction: "Enter the dollar amount.",
        difficulty: "medium",
        action_type: "type",
        requires_input: true,
        audio_text: "Type or choose the amount you would like to transfer.",
        action_data: {
          inputLabel: "Transfer Amount ($)",
          inputPlaceholder: "e.g. 50.00",
          inputType: "number",
          defaultValue: "75.00",
          choices: [
            { id: "amt_25", title: "$25.00", description: "Quick select" },
            { id: "amt_50", title: "$50.00", description: "Quick select" },
            { id: "amt_75", title: "$75.00", description: "Quick select" },
            { id: "amt_100", title: "$100.00", description: "Quick select" },
          ],
        },
      },
      {
        step_id: "STEP_BNK_03",
        task_id: "TASK_BNK_001",
        step_number: 3,
        instruction: "Choose your funding account for this transfer.",
        short_instruction: "Choose your account.",
        difficulty: "low",
        action_type: "select",
        requires_input: true,
        audio_text: "Select which of your bank accounts to pay from.",
        action_data: {
          choices: [
            { id: "acc_1", title: "Everyday Checking (•••• 8092)", description: "Available: $2,450.00 • No transfer fees", badge: "Primary", icon: "CreditCard" },
            { id: "acc_2", title: "High-Yield Savings (•••• 3319)", description: "Available: $12,800.00", icon: "Wallet" },
          ],
        },
      },
      {
        step_id: "STEP_BNK_04",
        task_id: "TASK_BNK_001",
        step_number: 4,
        instruction: "Review transfer details and verify security confirmation.",
        short_instruction: "Confirm the transfer.",
        difficulty: "low",
        action_type: "confirm",
        requires_input: true,
        audio_text: "Check that the recipient and amount are correct, then tap confirm.",
        action_data: {
          summaryItems: [
            { label: "Recipient", value: "Jordan Miller (Electric Utility)" },
            { label: "From Account", value: "Everyday Checking (•••• 8092)" },
            { label: "Amount", value: "$75.00" },
            { label: "Transfer Speed", value: "Instant (Within 60 seconds)" },
            { label: "Transfer Fee", value: "$0.00" },
          ],
        },
      },
    ],
  },
};

export function generateGenericSteps(taskTitle: string): { task: Task; steps: Step[] } {
  const taskId = `TASK_GEN_${Date.now()}`;
  return {
    task: {
      task_id: taskId,
      user_id: "USER_1027",
      original_input: taskTitle,
      input_mode: "text",
      normalized_task: taskTitle,
      status: "active",
      created_at: new Date().toISOString(),
      completed_at: "",
    },
    steps: [
      {
        step_id: `${taskId}_01`,
        task_id: taskId,
        step_number: 1,
        instruction: `Select your initial preference to begin "${taskTitle}".`,
        short_instruction: "Select starting option.",
        difficulty: "low",
        action_type: "click",
        requires_input: true,
        audio_text: `Step 1. Choose an option to get started with ${taskTitle}.`,
        action_data: {
          choices: [
            { id: "opt_1", title: "Standard Fast Setup", description: "Use recommended settings for standard completion", badge: "Recommended", icon: "Zap" },
            { id: "opt_2", title: "Guided Step-by-Step", description: "Extra detailed explanations with guided hints", icon: "HelpCircle" },
          ],
        },
      },
      {
        step_id: `${taskId}_02`,
        task_id: taskId,
        step_number: 2,
        instruction: `Review and specify the core requirements for your request.`,
        short_instruction: "Select main requirement.",
        difficulty: "medium",
        action_type: "select",
        requires_input: true,
        audio_text: "Step 2. Choose the specific item that applies to your goal.",
        action_data: {
          choices: [
            { id: "req_1", title: "Express processing (Online priority)", description: "Completed immediately without delay", badge: "Fast", icon: "CheckCircle2" },
            { id: "req_2", title: "Standard processing", description: "Standard turnaround time", icon: "Clock" },
          ],
        },
      },
      {
        step_id: `${taskId}_03`,
        task_id: taskId,
        step_number: 3,
        instruction: `Confirm your contact and notification preference.`,
        short_instruction: "How should we notify you?",
        difficulty: "low",
        action_type: "click",
        requires_input: true,
        audio_text: "Step 3. Choose how you would like to receive confirmations.",
        action_data: {
          choices: [
            { id: "notif_sms", title: "SMS Text Message (Mobile)", description: "Instant text alert with confirmation code", badge: "Fastest", icon: "MessageSquare" },
            { id: "notif_email", title: "Email Receipt", description: "Full digital receipt sent to your registered inbox", icon: "Mail" },
          ],
        },
      },
      {
        step_id: `${taskId}_04`,
        task_id: taskId,
        step_number: 4,
        instruction: `Review your request summary and confirm submission.`,
        short_instruction: "Review and submit.",
        difficulty: "low",
        action_type: "confirm",
        requires_input: true,
        audio_text: "Step 4. Everything is ready. Please confirm to finalize.",
        action_data: {
          summaryItems: [
            { label: "Task Goal", value: taskTitle },
            { label: "Processing Mode", value: "Express Online" },
            { label: "Notification", value: "SMS & Digital Receipt" },
            { label: "Status", value: "Verified & Ready to submit" },
          ],
        },
      },
    ],
  };
}
